/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Check the health status of the API
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        /**
         * CORS Preflight for Health Check
         * @description Handle CORS preflight requests for the health check endpoint
         */
        options: operations["optionsHealth"];
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description Retrieve a list of projects accessible to the authenticated user
         */
        get: operations["listProjects"];
        put?: never;
        /**
         * Create Project
         * @description Create a new project
         */
        post: operations["createProject"];
        delete?: never;
        /**
         * CORS Preflight for Projects
         * @description Handle CORS preflight requests for project endpoints
         */
        options: operations["optionsProjects"];
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project
         * @description Retrieve a specific project by ID
         */
        get: operations["getProject"];
        /**
         * Update Project
         * @description Update an existing project
         */
        put: operations["updateProject"];
        post?: never;
        /**
         * Delete Project
         * @description Delete a project and all its associated resources
         */
        delete: operations["deleteProject"];
        /**
         * CORS Preflight for Project
         * @description Handle CORS preflight requests for a specific project endpoint
         */
        options: operations["optionsProject"];
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Components
         * @description Retrieve components within a project
         */
        get: operations["listComponents"];
        put?: never;
        /**
         * Create Component
         * @description Create a new component within a project
         */
        post: operations["createComponent"];
        delete?: never;
        /**
         * CORS Preflight for Components
         * @description Handle CORS preflight requests for component endpoints
         */
        options: operations["optionsComponents"];
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/components/{componentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Component
         * @description Retrieve a specific component by ID
         */
        get: operations["getComponent"];
        /**
         * Update Component
         * @description Update an existing component. This endpoint supports optimistic concurrency
         *     control via ETags. Include the If-Match header with the ETag value from
         *     the most recent GET request to prevent concurrent modification conflicts.
         *
         */
        put: operations["updateComponent"];
        post?: never;
        delete?: never;
        /**
         * CORS Preflight for Component
         * @description Handle CORS preflight requests for a specific component endpoint
         */
        options: operations["optionsComponent"];
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /**
             * @description Health status of the API
             * @enum {string}
             */
            status: "healthy" | "unhealthy";
            /**
             * Format: date-time
             * @description Timestamp of the health check
             */
            timestamp: string;
            /**
             * @description API version
             * @example 0.1.0
             */
            version?: string;
            /**
             * @description API uptime in seconds
             * @example 3600
             */
            uptime?: number;
        };
        ErrorResponse: {
            /**
             * @description Error code
             * @example VALIDATION_ERROR
             */
            error: string;
            /**
             * @description Human-readable error message
             * @example Invalid request parameters
             */
            message: string;
            /**
             * Format: date-time
             * @description Timestamp when the error occurred
             */
            timestamp: string;
            /** @description Additional error details */
            details?: {
                [key: string]: unknown;
            };
            /**
             * @description Unique identifier for the request
             * @example req_123456789
             */
            requestId?: string;
        };
        Project: {
            /**
             * @description Unique identifier for the project
             * @example my-project
             */
            id: string;
            /**
             * @description Human-readable name for the project
             * @example My Project
             */
            name: string;
            /**
             * @description Optional description of the project
             * @example A sample project for demonstration
             */
            description?: string;
            status: components["schemas"]["ProjectStatus"];
            /**
             * @description Tags associated with the project
             * @example [
             *       "web",
             *       "api",
             *       "production"
             *     ]
             */
            tags?: string[];
            /** @description Additional metadata for the project */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Format: date-time
             * @description Timestamp when the project was created
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Timestamp when the project was last updated
             */
            updatedAt: string;
            /**
             * @description User ID who created the project
             * @example user_123
             */
            createdBy?: string;
        };
        /**
         * @description Status of the project
         * @enum {string}
         */
        ProjectStatus: "active" | "inactive" | "archived" | "deleted";
        CreateProjectRequest: {
            /**
             * @description Human-readable name for the project
             * @example My Project
             */
            name: string;
            /**
             * @description Optional description of the project
             * @example A sample project for demonstration
             */
            description?: string;
            /**
             * @description Tags associated with the project
             * @example [
             *       "web",
             *       "api",
             *       "production"
             *     ]
             */
            tags?: string[];
            /** @description Additional metadata for the project */
            metadata?: {
                [key: string]: unknown;
            };
        };
        UpdateProjectRequest: {
            /**
             * @description Human-readable name for the project
             * @example My Updated Project
             */
            name?: string;
            /**
             * @description Optional description of the project
             * @example An updated description
             */
            description?: string;
            status?: components["schemas"]["ProjectStatus"];
            /**
             * @description Tags associated with the project
             * @example [
             *       "web",
             *       "api",
             *       "production"
             *     ]
             */
            tags?: string[];
            /** @description Additional metadata for the project */
            metadata?: {
                [key: string]: unknown;
            };
        };
        ProjectListResponse: {
            projects: components["schemas"]["Project"][];
            /** @description Total number of projects matching the query */
            total: number;
            /** @description Maximum number of projects returned */
            limit: number;
            /** @description Number of projects skipped */
            offset: number;
        };
        Component: {
            /**
             * @description Unique identifier for the component
             * @example my-component
             */
            id: string;
            /**
             * @description Human-readable name for the component
             * @example My Component
             */
            name: string;
            /**
             * @description Optional description of the component
             * @example A sample component for demonstration
             */
            description?: string;
            type: components["schemas"]["ComponentType"];
            status: components["schemas"]["ComponentStatus"];
            /**
             * @description ID of the project this component belongs to
             * @example my-project
             */
            projectId?: string;
            /** @description Component configuration */
            config?: {
                [key: string]: unknown;
            };
            /** @description Additional metadata for the component */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Format: date-time
             * @description Timestamp when the component was created
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Timestamp when the component was last updated
             */
            updatedAt: string;
            /**
             * @description User ID who created the component
             * @example user_123
             */
            createdBy?: string;
        };
        /**
         * @description Type of the component
         * @enum {string}
         */
        ComponentType: "service" | "database" | "queue" | "cache" | "storage" | "api" | "worker" | "scheduler";
        /**
         * @description Status of the component
         * @enum {string}
         */
        ComponentStatus: "active" | "inactive" | "deploying" | "failed" | "pending";
        CreateComponentRequest: {
            /**
             * @description Human-readable name for the component
             * @example My Component
             */
            name: string;
            /**
             * @description Optional description of the component
             * @example A sample component for demonstration
             */
            description?: string;
            type: components["schemas"]["ComponentType"];
            /** @description Component configuration */
            config?: {
                [key: string]: unknown;
            };
            /** @description Additional metadata for the component */
            metadata?: {
                [key: string]: unknown;
            };
        };
        UpdateComponentRequest: {
            /**
             * @description Human-readable name for the component
             * @example My Updated Component
             */
            name?: string;
            /**
             * @description Optional description of the component
             * @example An updated description
             */
            description?: string;
            type?: components["schemas"]["ComponentType"];
            status?: components["schemas"]["ComponentStatus"];
            /** @description Component configuration */
            config?: {
                [key: string]: unknown;
            };
            /** @description Additional metadata for the component */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** @description Error response returned when a 409 Conflict occurs due to optimistic
         *     concurrency control. The resource has been modified since the client's
         *     last GET request, and the ETag in the If-Match header does not match
         *     the current resource version.
         *      */
        ConflictErrorResponse: {
            /**
             * @description Error code
             * @example CONCURRENT_MODIFICATION
             */
            error: string;
            /**
             * @description Human-readable error message
             * @example The resource has been modified since your last request. Please fetch the latest version and try again.
             */
            message: string;
            /**
             * Format: date-time
             * @description Timestamp when the conflict was detected
             */
            timestamp: string;
            /** @description Details about the concurrency conflict */
            conflict: {
                /**
                 * @description Type of resource that conflicted
                 * @example component
                 */
                resourceType: string;
                /**
                 * @description Identifier of the conflicting resource
                 * @example my-component
                 */
                resourceId: string;
                /**
                 * @description Current ETag value of the resource
                 * @example "xyz789"
                 */
                currentETag: string;
                /**
                 * @description ETag value provided in the If-Match header
                 * @example "abc123"
                 */
                providedETag: string;
            };
            /** @description Additional error details */
            details?: {
                [key: string]: unknown;
            };
            /**
             * @description Unique identifier for the request
             * @example req_123456789
             */
            requestId?: string;
        };
        ComponentListResponse: {
            components: components["schemas"]["Component"][];
            /** @description Total number of components matching the query */
            total: number;
            /** @description Maximum number of components returned */
            limit: number;
            /** @description Number of components skipped */
            offset: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description Allowed origin for CORS requests. In development, this is typically
         *     `http://localhost:5173`. In production, this will be the studio domain.
         *     The server may return `*` for public endpoints or a specific origin
         *     for authenticated requests.
         *      */
        AccessControlAllowOrigin: string;
        /** @description Comma-separated list of HTTP methods allowed for CORS requests.
         *     All endpoints support GET, POST, PUT, DELETE, and OPTIONS.
         *      */
        AccessControlAllowMethods: string;
        /** @description Comma-separated list of headers allowed in CORS requests.
         *     Includes Authorization (for Bearer tokens), Content-Type, X-API-Key, and If-Match (for optimistic concurrency control).
         *      */
        AccessControlAllowHeaders: string;
        /** @description Entity tag for optimistic concurrency control. The ETag is a quoted string
         *     that represents the current version of the resource. Clients should include
         *     this value in the If-Match header when updating the resource to prevent
         *     concurrent modification conflicts.
         *
         *     **Format:** The ETag value is always a quoted string (e.g., `"abc123"`).
         *     When comparing ETags, implementations must use strong comparison as per
         *     RFC 7232.
         *      */
        ETag: string;
        /** @description Conditional request header for optimistic concurrency control. The client
         *     must include the ETag value received from a previous GET request when
         *     updating a resource. If the ETag does not match the current resource
         *     version, the server will return a 409 Conflict response.
         *
         *     **Format:** The If-Match value must be a quoted string matching the ETag
         *     from the resource's last response. The value `*` can be used to match any
         *     existing resource, but this is not recommended for component updates.
         *      */
        IfMatch: string;
        /** @description Indicates whether credentials (cookies, authorization headers) are
         *     allowed in CORS requests. Must be the literal string "true" when
         *     credentials are supported.
         *
         *     **Implementation Note:** This header is **conditionally included** in
         *     responses. Implementations should only include this header when credentials
         *     are actually allowed for the specific request. When credentials are not
         *     allowed, this header must be omitted entirely (not set to "false").
         *
         *     **OpenAPI Specification:** Per OpenAPI 3.0, all response headers are
         *     optional by default. The presence of this header in the schema via `$ref`
         *     is for documentation purposes only and does not require implementations to
         *     include it in every response. Implementations must conditionally include
         *     this header based on request context and authentication requirements.
         *      */
        AccessControlAllowCredentials: "true";
        /** @description Maximum time (in seconds) that a browser can cache the preflight
         *     response. Default is 86400 (24 hours).
         *      */
        AccessControlMaxAge: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is healthy */
            200: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description API is unhealthy */
            503: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    optionsHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CORS preflight response */
            200: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Methods": components["headers"]["AccessControlAllowMethods"];
                    "Access-Control-Allow-Headers": components["headers"]["AccessControlAllowHeaders"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    "Access-Control-Max-Age": components["headers"]["AccessControlMaxAge"];
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listProjects: {
        parameters: {
            query?: {
                /** @description Maximum number of projects to return */
                limit?: number;
                /** @description Number of projects to skip */
                offset?: number;
                /** @description Filter projects by status */
                status?: components["schemas"]["ProjectStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of projects */
            200: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Project created successfully */
            201: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Project already exists */
            409: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    optionsProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CORS preflight response */
            200: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Methods": components["headers"]["AccessControlAllowMethods"];
                    "Access-Control-Allow-Headers": components["headers"]["AccessControlAllowHeaders"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    "Access-Control-Max-Age": components["headers"]["AccessControlMaxAge"];
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier for the project */
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project details */
            200: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier for the project */
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description Project updated successfully */
            200: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier for the project */
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project deleted successfully */
            204: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    optionsProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier for the project */
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CORS preflight response */
            200: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Methods": components["headers"]["AccessControlAllowMethods"];
                    "Access-Control-Allow-Headers": components["headers"]["AccessControlAllowHeaders"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    "Access-Control-Max-Age": components["headers"]["AccessControlMaxAge"];
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listComponents: {
        parameters: {
            query?: {
                /** @description Maximum number of components to return */
                limit?: number;
                /** @description Number of components to skip */
                offset?: number;
                /** @description Filter components by type */
                type?: components["schemas"]["ComponentType"];
            };
            header?: never;
            path: {
                /** @description Unique identifier for the project */
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of components */
            200: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComponentListResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createComponent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier for the project */
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateComponentRequest"];
            };
        };
        responses: {
            /** @description Component created successfully */
            201: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Component"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Component already exists */
            409: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    optionsComponents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier for the project */
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CORS preflight response */
            200: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Methods": components["headers"]["AccessControlAllowMethods"];
                    "Access-Control-Allow-Headers": components["headers"]["AccessControlAllowHeaders"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    "Access-Control-Max-Age": components["headers"]["AccessControlMaxAge"];
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getComponent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier for the project */
                projectId: string;
                /** @description Unique identifier for the component */
                componentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Component details */
            200: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Component"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Component not found */
            404: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateComponent: {
        parameters: {
            query?: never;
            header: {
                /** @description ETag value from the most recent GET request for this component.
                 *     The update will only proceed if the ETag matches the current resource version.
                 *      */
                "If-Match": string;
            };
            path: {
                /** @description Unique identifier for the project */
                projectId: string;
                /** @description Unique identifier for the component */
                componentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateComponentRequest"];
            };
        };
        responses: {
            /** @description Component updated successfully */
            200: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Component"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Component not found */
            404: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict - The resource has been modified since the last GET request.
             *     The ETag in the If-Match header does not match the current resource version.
             *     The client should fetch the latest version and retry the update.
             *      */
            409: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictErrorResponse"];
                };
            };
            /** @description Precondition Failed - The If-Match header is missing or invalid.
             *     The client must include a valid If-Match header with the ETag value.
             *      */
            412: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    optionsComponent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier for the project */
                projectId: string;
                /** @description Unique identifier for the component */
                componentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CORS preflight response */
            200: {
                headers: {
                    "Access-Control-Allow-Origin": components["headers"]["AccessControlAllowOrigin"];
                    "Access-Control-Allow-Methods": components["headers"]["AccessControlAllowMethods"];
                    "Access-Control-Allow-Headers": components["headers"]["AccessControlAllowHeaders"];
                    "Access-Control-Allow-Credentials": components["headers"]["AccessControlAllowCredentials"];
                    "Access-Control-Max-Age": components["headers"]["AccessControlMaxAge"];
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
