name: E2E Tests (Simple)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install

      - name: Generate API client types
        run: pnpm client:gen:ci

      - name: Build Studio
        run: pnpm build
        env:
          VITE_API_BASE_URL: http://localhost:3000

      - name: Start mock API
        run: |
          # Use the improved mock API server
          node mock-api-server.cjs &
          sleep 3

      - name: Install Playwright
        run: pnpm add -D @playwright/test

      - name: Install Playwright browsers
        run: pnpm dlx playwright install chromium

      - name: Start Studio preview server
        run: |
          pnpm preview --port 5173 --host 0.0.0.0 &
          sleep 5

      - name: Run E2E tests
        run: |
          STUDIO_BASE_URL=http://localhost:5173 \
          API_BASE_URL=http://localhost:3000 \
          pnpm playwright test tests/e2e/ --reporter=list

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
